name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build to Linux GNU
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo build --release --target ${{ matrix.target }}
      - name: Build to Linux MUSL
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          docker run --rm -t \
            -v "$(pwd)":/volume \
            clux/muslrust:stable \
            cargo build --release --target ${{ matrix.target }}
      - name: Pack binaries to tar.gz
        run: tar cvzf telegram_image_metadata-${{ github.ref_name }}-${{ matrix.target }}.tar.gz target/${{ matrix.target }}/release/telegram_image_metadata
      - name: Upload packaged binaries
        uses: actions/upload-artifact@v2
        with:
          name: telegram_image_metadata-${{ github.ref_name }}-${{ matrix.target }}
          path: |
            telegram_image_metadata-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
          if-no-files-found: error

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download
        uses: actions/download-artifact@v2
      - name: Layout
        run: |
          mv telegram_image_metadata-${{ github.ref_name }}-x86_64-unknown-linux-musl/telegram_image_metadata-${{ github.ref_name }}-x86_64-unknown-linux-musl.tar.gz ./telegram_image_metadata-${{ github.ref_name }}-musl.tar.gz
          mv telegram_image_metadata-${{ github.ref_name }}-x86_64-unknown-linux-gnu/telegram_image_metadata-${{ github.ref_name }}-x86_64-unknown-linux-gnu.tar.gz ./telegram_image_metadata-${{ github.ref_name }}-gnu.tar.gz

          rm -rf telegram_image_metadata-${{ github.ref_name }}-x86_64-unknown-linux-musl telegram_image_metadata-${{ github.ref_name }}-x86_64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          generate_release_notes: true
          draft: true
          fail_on_unmatched_files: true
          files: |
            telegram_image_metadata-${{ github.ref_name }}-musl.tar.gz
            telegram_image_metadata-${{ github.ref_name }}-gnu.tar.gz
